### ISSUE TITLE
i am confused bro

### ISSUE THREAD

**Issue by ViSioNSeC** [JDRobotter/wifi#2]
./run.py --gateway 192.168.1.245 --tcpdump --monitor wlan1mon --hostapds wlan0 --ignore 00:00:00:00:00 -p 8088
/root/test/wifi/logs/8056911625724996/wifis.log ./logs/lastlog
11:01:36  [+] Clearing iptables rules
11:01:36  Using wlan0 with 1 virtuals ap
11:01:36  [+] Setting up NAT on 192.168.1.245
11:01:36  Database: using clients.db
11:01:36  [+] Starting ADMIN server on port 8088
global name 'sniff' is not defined
  File "./run.py", line 186, in <module>
    km.do_sniff()
Traceback (most recent call last):
  File "./run.py", line 186, in <module>
    km.do_sniff()
  File "/root/test/wifi/src/Karma2.py", line 370, in do_sniff
    sniff(prn=_filter,store=0)
NameError: global name 'sniff' is not defined

**Comment by mehdilauters-td** [comment]
Hi
Did you install [scapy](http://www.secdev.org/projects/scapy/) ?

**Comment by ViSioNSeC** [comment]
pip install scapy
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages

**Comment by mehdilauters** [comment]
This was some refactoring issue as I mainly use the [wifiScanMap](https://github.com/mehdilauters/wifiScanMap/) scanning tool.
Hope the fix helps
